site_name: Mesfin | IT Portfolio

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: black
      accent: cyan

plugins:
  - search

nav:
  - Home: index.md
  - Experience: experience.md
  - Skills: skills.md
  - Projects: projects.md
  - Architecture: architecture.md
  - Blog: blog.md
  - Contact: contact.md